void addm(Matrix, Matrix);
void subm(Matrix, Matrix);
void mulm(Matrix, Matrix);
void transm(Matrix);
double detm(Matrix);
Vector mulvecm(Vector, Matrix);
Vector Vec(double, double, double);
Vector addvec(Vector, Vector);
Vector subvec(Vector, Vector);
Vector mulvec(Vector, double);
double dotvec(Vector, Vector);
Vector normvec(Vector);
double round(double);
double hypot3(double, double, double);
void *emalloc(ulong);
