.TH TEMP 1
.SH NAME
temp \- temperature converter
.SH SYNOPSIS
.B conv/temp
[
.B -i 
.I scale
]
[
.B -o
.I scale
]
.I temp
.SH DESCRIPTION
.I Temp
is a basic temperature converter.
.PP
.I Scale
can be one of C(elsius), F(ahrenheit) and K(elvin).  If none is
specified
.B temp
will use the default F for input, C for output scales.
.SH EXAMPLES
.PP
Convert from celsius to fahrenheit
.IP
.EX
% conv/temp -iC -oF 234.78
454.604
.EE
.SH SOURCE
.B /sys/src/cmd/conv
.SH BUGS
.IR none .
